# Generated by Django 2.2 on 2019-04-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaBarberia', '0006_auto_20190409_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(),
        ),
    ]
