# Generated by Django 2.2 on 2019-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaBarberia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbero',
            name='fotobarbero',
            field=models.ImageField(null=True, upload_to='fotosbarberos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotosclientes'),
        ),
    ]
