# Generated by Django 2.2 on 2019-05-03 17:45

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('ReservaBarberia', '0003_auto_20190503_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=255, verbose_name='Correo'),
        ),
    ]
